let passengers = {
            poland:{ 
                "sweden": 22,
                "norway": 5,
                "denmark": 5,
                "greatBritain": 55,
                "lithuania": 41,
                "latvia": 38,
                "estonia": 30,
                "ussr": 70,
                "finland": 25,
                "germany": 80,
                "netherland": 7,
                "belgium": 5,
                "france": 42,
                "spain": 29,
                "portugal": 12,
                "italy": 22,
                "yugoslavia": 18,
                "albania": 2,
                "greece": 5,
                "turkey": 5,
                "bulgaria": 3,
                "romania": 32,
                "iceland": 2,
                "ireland" : 2,
                "czechoslovakia": 35,
                "hungary": 28,
                "austria" : 15,
                "switzerland" : 8,
                "sardynia" : 12,
                "sicily" : 15,
                "corsica" : 8,
                "eastPrussia" : 30,
                "algieria" : 1
            },
            sweden:{ 
                "poland": 18,
                "norway": 55,
                "denmark": 57,
                "greatBritain": 41,
                "lithuania": 12, 
                "latvia": 18,
                "estonia": 17,
                "ussr": 25, 
                "finland": 52,
                "germany": 44, 
                "netherland": 32,
                "belgium": 12, 
                "france": 23, 
                "spain": 18, 
                "portugal": 12, 
                "italy": 15, 
                "yugoslavia": 8, 
                "albania": 1, 
                "greece": 3, 
                "turkey": 3, 
                "bulgaria": 5,
                "romania": 12, 
                "iceland": 5, 
                "ireland" : 5 ,
                "czechoslovakia": 3,
                "hungary": 2,
                "austria" : 2,
                "switzerland" : 12,
                "sardynia" : 1,
                "sicily" : 2,
                "corsica" : 2,
                "eastPrussia" : 20,
                "algieria" : 1
            },
            finland:{ 
                "poland": 12,
                "sweden": 61,
                "denmark": 20,
                "greatBritain": 15,
                "lithuania": 8,
                "latvia": 12,
                "estonia": 44,
                "ussr": 38,
                "norway": 40, 
                "germany": 33,
                "netherland": 3,
                "belgium": 2,
                "france": 12,
                "spain": 8,
                "portugal": 3,
                "italy": 5,
                "yugoslavia": 5,
                "albania": 1,
                "greece": 2,
                "turkey": 2,
                "bulgaria": 1,
                "romania": 1,
                "iceland": 5,
                "ireland" : 1,
                "czechoslovakia": 1,
                "hungary": 1,
                "austria" : 2,
                "switzerland" : 12,
                "sardynia" : 1,
                "sicily" : 5,
                "corsica" : 4,
                "eastPrussia" : 12,
                "algieria" : 1
            },
            denmark:{ 
                "poland": 50,
                "sweden": 79,
                "finland": 10,
                "greatBritain": 14,
                "lithuania": 58,
                "latvia": 85,
                "estonia": 97,
                "ussr": 124,
                "norway": 50,
                "germany": 46,
                "netherland": 15,
                "belgium": 30,
                "france": 15,
                "spain": 28,
                "portugal": 31,
                "italy": 9,
                "yugoslavia": 96,
                "albania": 11,
                "greece": 83,
                "turkey": 74,
                "bulgaria": 50,
                "romania": 37,
                "iceland": 31,
                "ireland" : 61,
                "czechoslovakia": 350,
                "hungary": 80,
                "austria" : 150,
                "switzerland" : 35,
                "sardynia" : 50,
                "sicily" : 30,
                "corsica" : 80,
                "eastPrussia" : 100,
                "algieria" : 10
            },
            greatBritain:{ 
                "poland": 79,
                "sweden": 22,
                "finland": 25,
                "denmark": 14,
                "lithuania": 24, 
                "latvia": 23,
                "estonia": 24,
                "ussr": 26,
                "norway": 14, 
                "germany": 93,
                "netherland": 58,
                "belgium": 45,
                "france": 155,
                "spain": 101,
                "portugal": 16,
                "italy": 36,
                "yugoslavia": 48,
                "albania": 44,
                "greece": 55,
                "turkey": 46,
                "bulgaria": 22,
                "romania": 9,
                "iceland": 42,
                "ireland" : 22,
                "czechoslovakia": 35,
                "hungary":20,
                "austria" : 15,
                "switzerland" : 35,
                "sardynia" : 50,
                "sicily" : 30,
                "corsica" : 80,
                "eastPrussia" : 100,
                "algieria" : 10
            },
            lithuania:{ 
                "poland": 21,
                "sweden": 49,
                "finland": 62,
                "denmark": 59,
                "greatBritain": 24, 
                "latvia": 40, 
                "estonia": 56,
                "ussr": 87,
                "norway": 16, 
                "germany": 88,
                "netherland": 16,
                "belgium": 13,
                "france": 21,
                "spain": 21,
                "portugal": 36,
                "italy": 56,
                "yugoslavia": 83,
                "albania": 03,
                "greece": 70,
                "turkey": 52,
                "bulgaria": 74,
                "romania": 10,
                "iceland": 28,
                "ireland" : 24,
                "czechoslovakia": 35,
                "hungary":28,
                "austria" : 15,
                "switzerland" : 16,
                "sardynia" : 5,
                "sicily" : 3,
                "corsica" : 8,
                "eastPrussia" : 120,
                "algieria" : 10
            },
            latvia:{ 
                "poland": 14,
                "sweden": 92,
                "finland": 85,
                "denmark": 85,
                "greatBritain": 25, 
                "lithuania": 43, 
                "estonia": 51,
                "ussr": 84,
                "norway": 17, 
                "germany": 11,
                "netherland": 19,
                "belgium": 21,
                "france": 23,
                "spain": 32,
                "portugal": 33,
                "italy": 51,
                "yugoslavia": 70,
                "albania": 66,
                "greece": 78,
                "turkey": 70,
                "bulgaria": 72,
                "romania": 78,
                "iceland": 33,
                "ireland" : 27,
                "czechoslovakia": 35,
                "hungary":28,
                "austria" : 15,
                "switzerland" : 15,
                "sardynia" : 50,
                "sicily" : 30,
                "corsica" : 80,
                "eastPrussia" : 120,
                "algieria" : 10
            },
            estonia:{ 
                "poland": 71,
                "sweden": 41,
                "finland": 88,
                "denmark": 97,
                "greatBritain": 246, 
                "lithuania": 57, 
                "latvia": 53,
                "ussr": 34,
                "norway": 14, 
                "germany": 17,
                "netherland": 20,
                "belgium": 22,
                "france": 28,
                "spain": 38,
                "portugal": 32,
                "italy": 60,
                "yugoslavia": 70,
                "albania": 60,
                "greece": 77,
                "turkey": 79,
                "bulgaria": 11,
                "romania": 97,
                "iceland": 32,
                "ireland" : 28,
                "czechoslovakia": 30,
                "hungary":20,
                "austria" : 10,
                "switzerland" : 16,
                "sardynia" : 50,
                "sicily" : 30,
                "corsica" : 80,
                "eastPrussia" : 10,
                "algieria" : 10
            },
            ussr:{ 
                "poland": 160,
                "sweden": 70,
                "finland": 36,
                "denmark": 12,
                "greatBritain": 27, 
                "lithuania": 87, 
                "latvia": 83,
                "estonia": 34,
                "norway": 17, 
                "germany": 15,
                "netherland": 23,
                "belgium": 25,
                "france": 27,
                "spain": 36,
                "portugal": 42,
                "italy": 62,
                "yugoslavia": 74,
                "albania": 76,
                "greece": 74,
                "turkey": 80,
                "bulgaria": 82,
                "romania": 83,
                "iceland": 35,
                "ireland" : 31,
                "czechoslovakia": 50,
                "hungary":8,
                "austria" : 15,
                "switzerland" : 16,
                "sardynia" : 50,
                "sicily" : 30,
                "corsica" : 80,
                "eastPrussia" : 12,
                "algieria" : 10
            },
            norway:{ 
                "poland": 96,
                "sweden": 12,
                "denmark": 50,
                "greatBritain": 14,
                "lithuania": 12,
                "latvia": 13,
                "estonia": 14,
                "ussr": 17,
                "finland": 16,
                "germany": 84,
                "netherland": 70,
                "belgium": 16,
                "france": 14,
                "spain": 23,
                "portugal": 26,
                "italy": 50,
                "yugoslavia": 62,
                "albania": 58,
                "greece": 61,
                "turkey": 67,
                "bulgaria": 70,
                "romania": 71,
                "iceland": 21,
                "ireland" : 17,
                "czechoslovakia": 30,
                "hungary":20,
                "austria" : 10,
                "switzerland" : 16,
                "sardynia" : 50,
                "sicily" : 30,
                "corsica" : 80,
                "eastPrussia" : 10,
                "algieria" : 10
            },
            germany:{ 
                "poland": 83,
                "sweden": 18,
                "finland": 15,
                "denmark": 146,
                "greatBritain": 93,
                "lithuania": 88,
                "latvia": 11,
                "estonia": 12,
                "ussr": 84,
                "norway": 24,
                "netherland": 92,
                "belgium": 73,
                "france": 296,
                "spain": 186,
                "portugal": 24,
                "italy": 91,
                "yugoslavia": 61,
                "albania": 5,
                "greece": 56,
                "turkey": 60,
                "bulgaria": 62,
                "romania": 65,
                "iceland": 22,
                "ireland" : 17,
                "czechoslovakia": 35,
                "hungary":28,
                "austria" : 15,
                "switzerland" : 35,
                "sardynia" : 25,
                "sicily" : 30,
                "corsica" : 50,
                "eastPrussia" : 320,
                "algieria" : 10
            },
            netherland:{ 
                "poland": 15,
                "sweden": 18,
                "finland": 20,
                "denmark": 59,
                "greatBritain": 51,
                "lithuania": 16,
                "latvia": 18,
                "estonia": 20,
                "ussr": 23,
                "norway": 97,
                "germany": 92,
                "belgium": 126,
                "france": 258,
                "spain": 145,
                "portugal": 103,
                "italy": 40,
                "yugoslavia": 52,
                "albania": 4,
                "greece": 52,
                "turkey": 58,
                "bulgaria": 12,
                "romania": 17,
                "iceland": 21,
                "ireland" : 11,
                "czechoslovakia": 3,
                "hungary":2,
                "austria" : 1,
                "switzerland" : 16,
                "sardynia" : 5,
                "sicily" : 3,
                "corsica" : 8,
                "eastPrussia" : 12,
                "algieria" : 1
            },
            belgium:{ 
                "poland": 17,
                "sweden": 20,
                "finland": 23,
                "denmark": 13,
                "greatBritain": 47,
                "lithuania": 18,
                "latvia": 21,
                "estonia": 22,
                "ussr": 25,
                "norway": 12,
                "germany": 79,
                "netherland": 126,
                "france": 116,
                "spain": 14,
                "portugal": 19,
                "italy": 40,
                "yugoslavia": 52,
                "albania": 48,
                "greece": 51,
                "turkey": 57,
                "bulgaria": 60,
                "romania": 61,
                "iceland": 22,
                "ireland" : 11,
                "czechoslovakia": 35,
                "hungary":28,
                "austria" : 15,
                "switzerland" : 16,
                "sardynia" : 5,
                "sicily" : 3,
                "corsica" : 8,
                "eastPrussia" : 12,
                "algieria" : 1
            },
            france:{ 
                "poland": 27,
                "sweden": 26,
                "finland": 25,
                "denmark": 15,
                "greatBritain": 215,
                "lithuania": 20,
                "latvia": 23,
                "estonia": 24,
                "ussr": 27,
                "norway": 14,
                "germany": 369,
                "netherland": 158,
                "belgium": 116,
                "spain": 91,
                "portugal": 49,
                "italy": 154,
                "yugoslavia": 12,
                "albania": 2,
                "greece": 69,
                "turkey": 52,
                "bulgaria": 55,
                "romania": 56,
                "iceland": 12,
                "ireland" : 6,
                "czechoslovakia": 35,
                "hungary":28,
                "austria" : 15,
                "switzerland" : 163,
                "sardynia" : 50,
                "sicily" : 55,
                "corsica" : 180,
                "eastPrussia" : 12,
                "algieria" : 50
            },
            spain:{ 
                "poland": 20,
                "sweden": 32,
                "finland": 36,
                "denmark": 24,
                "greatBritain": 121,
                "lithuania": 29,
                "latvia": 32,
                "estonia": 33,
                "ussr": 36,
                "norway": 23,
                "germany": 55,
                "netherland": 14,
                "belgium": 14,
                "france": 152,
                "portugal": 206,
                "italy": 117,
                "yugoslavia": 4,
                "albania": 3,
                "greece": 41,
                "turkey": 48,
                "bulgaria": 1,
                "romania": 4,
                "iceland": 2,
                "ireland" : 13,
                "czechoslovakia": 3,
                "hungary":2,
                "austria" : 1,
                "switzerland" : 1,
                "sardynia" : 50,
                "sicily" : 53,
                "corsica" : 55,
                "eastPrussia" : 7,
                "algieria" : 12
            },
            portugal:{ 
                "poland": 34,
                "sweden": 13,
                "finland": 40,
                "denmark": 31,
                "greatBritain": 163,
                "lithuania": 3,
                "latvia": 3,
                "estonia": 2,
                "ussr": 4,
                "norway": 2,
                "germany": 24,
                "netherland": 20,
                "belgium": 19,
                "france": 53,
                "spain": 156,
                "italy": 21,
                "yugoslavia": 6,
                "albania": 2,
                "greece": 32,
                "turkey": 38,
                "bulgaria": 2,
                "romania": 4,
                "iceland": 2,
                "ireland" : 17,
                "czechoslovakia": 3,
                "hungary":2,
                "austria" : 15,
                "switzerland" : 16,
                "sardynia" : 12,
                "sicily" : 21,
                "corsica" : 22,
                "eastPrussia" : 1,
                "algieria" : 18
            },
            italy:{ 
                "poland": 22,
                "sweden": 58,
                "finland": 28,
                "denmark": 10,
                "greatBritain": 168,
                "lithuania": 3,
                "latvia": 5,
                "estonia": 6,
                "ussr": 66,
                "norway": 5,
                "germany": 44,
                "netherland": 42,
                "belgium": 43,
                "france": 35,
                "spain": 31,
                "portugal": 29,
                "yugoslavia": 37,
                "albania": 30,
                "greece": 25,
                "turkey": 23,
                "bulgaria": 26,
                "romania": 27,
                "iceland": 5,
                "ireland" : 8,
                "czechoslovakia": 22,
                "hungary":28,
                "austria" : 30,
                "switzerland" : 23,
                "sardynia" : 88,
                "sicily" : 133,
                "corsica" : 87,
                "eastPrussia" : 12,
                "algieria" : 34
            },
            yugoslavia:{
                "poland": 23,
                "sweden": 15,
                "finland": 11,
                "denmark": 13,
                "greatBritain": 33,
                "lithuania": 2,
                "latvia": 3,
                "estonia": 2,
                "ussr": 15,
                "norway": 11,
                "germany": 35,
                "netherland": 15,
                "belgium": 14,
                "france": 28,
                "spain": 25,
                "portugal": 18,
                "italy": 45,
                "albania": 22,
                "greece": 25,
                "turkey": 26,
                "bulgaria": 28,
                "romania": 35,
                "iceland": 1,
                "ireland" : 2,
                "czechoslovakia": 31,
                "hungary": 30,
                "austria" : 28,
                "switzerland" : 23,
                "sardynia" : 5,
                "sicily" : 3,
                "corsica" : 8,
                "eastPrussia" : 3,
                "algieria" : 1
            },
            albania:{ 
                "poland": 1,
                "sweden": 3,
                "finland": 1,
                "denmark": 1,
                "greatBritain": 7,
                "lithuania": 1,
                "latvia": 1,
                "estonia": 1,
                "ussr": 4,
                "norway": 1,
                "germany": 11,
                "netherland": 1,
                "belgium": 1,
                "france": 3,
                "spain": 2,
                "portugal": 1,
                "italy": 22,
                "yugoslavia": 15,
                "greece": 18,
                "turkey": 12,
                "bulgaria": 11,
                "romania": 8,
                "iceland": 1,
                "ireland" : 1,
                "czechoslovakia": 2,
                "hungary": 3,
                "austria" : 2,
                "switzerland" : 1,
                "sardynia" : 1,
                "sicily" : 1,
                "corsica" : 1,
                "eastPrussia" : 1,
                "algieria" : 1
            },
            greece:{ 
                "poland": 5,
                "sweden": 5,
                "finland": 3,
                "denmark": 5,
                "greatBritain": 52,
                "lithuania": 2,
                "latvia": 3,
                "estonia": 2,
                "ussr": 15,
                "norway": 3,
                "germany": 45,
                "netherland": 10,
                "belgium": 8,
                "france": 40,
                "spain": 42,
                "portugal": 12,
                "italy": 55,
                "yugoslavia": 40,
                "albania": 35,
                "turkey": 35,
                "bulgaria": 30,
                "romania": 28,
                "iceland": 1,
                "ireland" : 1,
                "czechoslovakia": 3,
                "hungary": 3,
                "austria" : 3,
                "switzerland" : 5,
                "sardynia" : 8,
                "sicily" : 7,
                "corsica" : 5,
                "eastPrussia" : 1,
                "algieria" : 3
            },
            turkey:{ 
                "poland": 7,
                "sweden": 5,
                "finland": 3,
                "denmark": 4,
                "greatBritain": 31,
                "lithuania": 2,
                "latvia": 2,
                "estonia": 1,
                "ussr": 25,
                "norway": 1,
                "germany": 51,
                "netherland": 2,
                "belgium": 3,
                "france": 32,
                "spain": 23,
                "portugal": 22,
                "italy": 25,
                "yugoslavia": 22,
                "albania": 23,
                "greece": 31,
                "bulgaria": 34,
                "romania": 30,
                "iceland": 2,
                "ireland" : 2,
                "czechoslovakia": 5,
                "hungary": 7,
                "austria" : 5,
                "switzerland" : 3,
                "sardynia" : 5,
                "sicily" : 7,
                "corsica" : 5,
                "eastPrussia" : 31,
                "algieria" : 30
            },
            bulgaria:{ 
                "poland": 5,
                "sweden": 1,
                "finland": 1,
                "denmark": 1,
                "greatBritain": 12,
                "lithuania": 1,
                "latvia": 1,
                "estonia": 1,
                "ussr": 22,
                "norway": 1,
                "germany": 18,
                "netherland": 3,
                "belgium": 2,
                "france": 13,
                "spain": 8,
                "portugal": 5,
                "italy": 17,
                "yugoslavia": 43,
                "albania": 22,
                "greece": 45,
                "turkey": 71,
                "romania": 80,
                "iceland": 1,
                "ireland" : 1,
                "czechoslovakia": 18,
                "hungary": 28,
                "austria" : 21,
                "switzerland" : 16,
                "sardynia" : 5,
                "sicily" : 8,
                "corsica" : 7,
                "eastPrussia" : 2,
                "algieria" : 18
            },
            romania:{ 
                "poland": 41,
                "sweden": 5,
                "finland": 3,
                "denmark": 4,
                "greatBritain": 22,
                "lithuania": 1,
                "latvia": 1,
                "estonia": 1,
                "ussr": 38,
                "norway": 1,
                "germany": 22,
                "netherland": 11,
                "belgium": 9,
                "france": 21,
                "spain": 13,
                "portugal": 8,
                "italy": 18,
                "yugoslavia": 38,
                "albania": 35,
                "greece": 22,
                "turkey": 22,
                "bulgaria": 71,
                "iceland": 1,
                "ireland" : 1,
                "czechoslovakia": 35,
                "hungary": 71,
                "austria" : 55,
                "switzerland" : 15,
                "sardynia" : 2,
                "sicily" : 3,
                "corsica" : 8,
                "eastPrussia" : 12,
                "algieria" : 3
            },
            iceland:{ 
                "poland": 3,
                "sweden": 3,
                "finland": 3,
                "denmark": 2,
                "greatBritain": 23,
                "lithuania": 1,
                "latvia": 1,
                "estonia": 1,
                "ussr": 15,
                "norway": 1,
                "germany": 20,
                "netherland": 5,
                "belgium": 3,
                "france": 12,
                "spain": 13,
                "portugal": 5,
                "italy": 5,
                "yugoslavia": 1,
                "albania": 1,
                "greece": 2,
                "turkey": 1,
                "bulgaria": 1,
                "romania": 1,
                "ireland" : 1,
                "czechoslovakia": 2,
                "hungary": 2,
                "austria" : 1,
                "switzerland" : 5,
                "sardynia" : 1,
                "sicily" : 1,
                "corsica" : 1,
                "eastPrussia" : 3,
                "algieria" : 1
            },
            ireland:{ 
                "poland": 12,
                "sweden": 8,
                "finland": 5,
                "denmark": 7,
                "greatBritain": 122,
                "lithuania": 2, 
                "latvia": 1,
                "estonia": 1,
                "ussr": 13,
                "norway": 22, 
                "germany": 31,
                "netherland": 18,
                "belgium": 5,
                "france": 31,
                "spain": 11,
                "portugal": 5,
                "italy": 12,
                "yugoslavia": 4,
                "albania": 1,
                "greece": 3,
                "turkey": 5,
                "bulgaria": 2,
                "romania": 5,
                "iceland": 5 ,
                "czechoslovakia": 3,
                "hungary":2,
                "austria" : 1,
                "switzerland" : 13,
                "sardynia" : 22,
                "sicily" : 10,
                "corsica" : 20,
                "eastPrussia" : 12,
                "algieria" : 1
            },
            czechoslovakia:{ 
                "poland": 55,
                "sweden": 11,
                "finland": 8,
                "denmark": 8,
                "greatBritain": 28,
                "lithuania": 8, 
                "latvia": 7,
                "estonia": 5,
                "ussr": 18,
                "norway": 5, 
                "germany": 82,
                "netherland": 7,
                "belgium": 6,
                "france": 31,
                "spain": 18,
                "portugal": 12,
                "italy": 31,
                "yugoslavia": 35,
                "albania": 5,
                "greece": 5,
                "turkey": 5,
                "bulgaria": 5,
                "romania": 30,
                "iceland": 1,
                "hungary": 45,
                "austria": 42,
                "switzerland" : 22,
                "ireland" : 2,
                "sardynia" : 2,
                "sicily" : 2,
                "corsica" : 2,
                "eastPrussia" : 31,
                "algieria" : 1
            },
            hungary:{ 
                "poland": 41,
                "sweden": 12,
                "finland": 5,
                "denmark": 7,
                "greatBritain": 22,
                "lithuania": 3, 
                "latvia": 3,
                "estonia": 2,
                "ussr": 25,
                "norway": 2, 
                "germany": 25,
                "netherland": 3,
                "belgium": 2,
                "france": 23,
                "spain": 17,
                "portugal": 6,
                "italy": 21,
                "yugoslavia": 63,
                "albania": 12,
                "greece": 15,
                "turkey": 15,
                "bulgaria": 22,
                "romania": 55,
                "iceland": 1 ,
                "czechoslovakia": 52,
                "austria": 72,
                "switzerland" : 18,
                "ireland" : 1,
                "sardynia" : 1,
                "sicily" : 1,
                "corsica" : 1,
                "eastPrussia" : 12,
                "algieria" : 1
            },
            austria:{ 
                "poland": 5,
                "sweden": 4,
                "finland": 3,
                "denmark": 4,
                "greatBritain": 28,
                "lithuania": 7, 
                "latvia": 6,
                "estonia": 5,
                "ussr": 24,
                "norway": 2, 
                "germany": 120,
                "netherland": 3,
                "belgium": 2,
                "france": 12,
                "spain": 7,
                "portugal": 3,
                "italy": 71,
                "yugoslavia": 45,
                "albania": 2,
                "greece": 2,
                "turkey": 2,
                "bulgaria": 2,
                "romania": 3,
                "iceland": 1 ,
                "czechoslovakia": 45,
                "hungary": 88,
                "switzerland" : 45,
                "ireland" : 1,
                "sardynia" : 1,
                "sicily" : 1,
                "corsica" : 1,
                "eastPrussia" : 12,
                "algieria" : 1
            },
            switzerland:{ 
                "poland": 12,
                "sweden": 7,
                "finland": 3,
                "denmark": 3,
                "greatBritain": 48,
                "lithuania": 1, 
                "latvia": 1,
                "estonia": 1,
                "ussr": 45,
                "norway": 1, 
                "germany": 123,
                "netherland": 21,
                "belgium": 18,
                "france": 112,
                "spain": 5,
                "portugal": 3,
                "italy": 80,
                "yugoslavia": 31,
                "albania": 2,
                "greece": 31,
                "turkey": 28,
                "bulgaria": 2,
                "romania": 3,
                "iceland": 3 ,
                "czechoslovakia": 12,
                "hungary": 3,
                "austria" : 22,
                "ireland" : 1,
                "sardynia" : 22,
                "sicily" : 10,
                "corsica" : 1,
                "eastPrussia" : 5,
                "algieria" : 1
            },
            eastPrussia:{ 
                "poland": 71,
                "sweden": 31,
                "finland": 22,
                "denmark": 23,
                "greatBritain": 15,
                "lithuania": 55, 
                "latvia": 5,
                "estonia": 7,
                "ussr": 12,
                "norway": 13, 
                "germany": 160,
                "netherland": 21,
                "belgium": 3,
                "france": 5,
                "spain": 17,
                "portugal": 2,
                "italy": 23,
                "yugoslavia": 2,
                "albania": 1,
                "greece": 2,
                "turkey": 12,
                "bulgaria": 2,
                "romania": 2,
                "iceland": 1 ,
                "czechoslovakia": 3,
                "hungary":3,
                "austria" : 15,
                "ireland" : 1,
                "sardynia" : 1,
                "sicily" : 1,
                "corsica" : 1,
                "algieria" : 1
            },
            corsica:{ 
                "poland": 2,
                "sweden": 2,
                "finland": 2,
                "denmark": 1,
                "greatBritain": 5,
                "lithuania": 3, 
                "latvia": 2,
                "estonia": 2,
                "ussr": 7,
                "norway": 2, 
                "germany": 6,
                "netherland": 2,
                "belgium": 2,
                "france": 22,
                "spain": 8,
                "portugal": 3,
                "italy": 12,
                "yugoslavia": 3,
                "albania": 1,
                "greece": 3,
                "turkey": 3,
                "bulgaria": 2,
                "romania": 2,
                "iceland": 1 ,
                "czechoslovakia": 1,
                "hungary":1,
                "austria" : 1,
                "ireland" : 1,
                "sardynia" : 2,
                "sicily" : 2,
                "eastPrussia" : 1,
                "algieria" : 1
            },
            algieria:{ 
                "poland": 2,
                "sweden": 1,
                "finland": 1,
                "denmark": 1,
                "greatBritain": 5,
                "lithuania": 1, 
                "latvia": 1,
                "estonia": 1,
                "ussr": 3,
                "norway": 1, 
                "germany": 3,
                "netherland": 1,
                "belgium": 1,
                "france": 21,
                "spain": 12,
                "portugal": 7,
                "italy": 5,
                "yugoslavia": 3,
                "albania": 3,
                "greece": 3,
                "turkey": 3,
                "bulgaria": 2,
                "romania": 2,
                "iceland": 1 ,
                "czechoslovakia": 1,
                "hungary": 1,
                "austria" : 1,
                "ireland" : 1,
                "sardynia" : 1,
                "sicily" : 2,
                "corsica" : 1,
                "eastPrussia" : 1
            },
            sicily:{ 
                "poland": 2,
                "sweden": 2,
                "finland": 2,
                "denmark": 2,
                "greatBritain": 5,
                "lithuania": 1, 
                "latvia": 1,
                "estonia": 1,
                "ussr": 3,
                "norway": 1, 
                "germany": 12,
                "netherland": 1,
                "belgium": 1,
                "france": 5,
                "spain": 7,
                "portugal": 3,
                "italy": 88,
                "yugoslavia": 31,
                "albania": 30,
                "greece": 7,
                "turkey": 6,
                "bulgaria": 5,
                "romania": 3,
                "iceland": 1 ,
                "czechoslovakia": 1,
                "hungary": 2,
                "austria" : 1,
                "ireland" : 1,
                "sardynia" : 28,
                "corsica" : 20,
                "eastPrussia" : 7,
                "algieria" : 5
            },
            sardynia:{ 
                "poland": 1,
                "sweden": 1,
                "finland": 1,
                "denmark": 1,
                "greatBritain": 5,
                "lithuania": 1, 
                "latvia": 1,
                "estonia": 1,
                "ussr": 3,
                "norway": 1, 
                "germany": 8,
                "netherland": 2,
                "belgium": 1,
                "france": 3,
                "spain": 5,
                "portugal": 2,
                "italy": 37,
                "yugoslavia": 22,
                "albania": 12,
                "greece": 13,
                "turkey": 12,
                "bulgaria": 5,
                "romania": 3,
                "iceland": 1 ,
                "czechoslovakia": 1,
                "hungary":2,
                "austria" : 1,
                "ireland" : 1,
                "sicily" : 22,
                "corsica" : 2,
                "eastPrussia" : 2,
                "algieria" : 3
            }
}