export let relations = { /// max 100 min -100
    poland:{ 
        "sweden": 0,
        "norway": 0,
        "denmark": 0,
        "greatBritain": 45,
        "lithuania": -30,
        "latvia": 25,
        "estonia": 27,
        "ussr": -10,
        "finland": 10,
        "germany": 5,
        "netherland": 2,
        "belgium": 1,
        "france": 50,
        "spain": 2,
        "portugal": 1,
        "italy": 17,
        "yugoslavia": 21,
        "albania": 0,
        "greece": 0,
        "turkey": 0,
        "bulgaria": 0,
        "romania": 41,
        "iceland": 3,
        "ireland" : 0,
        "czechoslovakia": -5,
        "hungary": 40,
        "austria" : 5,
        "switzerland" : 12,
        "sardynia" : 1,
        "sicily" : 2,
        "corsica" : 2,
        "eastPrussia" : -30,
        "algieria" : 2
    },
    sweden:{ 
        "poland": 0,
        "norway": 20,
        "denmark": 20,
        "greatBritain": 5,
        "lithuania": 5, 
        "latvia": 7,
        "estonia": 8,
        "ussr": 10, 
        "finland": 18,
        "germany": 10, 
        "netherland": 10,
        "belgium": 8, 
        "france": 17, 
        "spain": 15, 
        "portugal": 10, 
        "italy": 10, 
        "yugoslavia": 5, 
        "albania": 1, 
        "greece": 3, 
        "turkey": 3, 
        "bulgaria": 5,
        "romania": 12, 
        "iceland": 5, 
        "ireland" : 5 ,
        "czechoslovakia": 3,
        "hungary": 2,
        "austria" : 2,
        "switzerland" : 10,
        "sardynia" : 1,
        "sicily" : 2,
        "corsica" : 2,
        "eastPrussia" : 5,
        "algieria" : 1
    },
    finland:{ 
        "poland": 10,
        "sweden": 18,
        "denmark": 17,
        "greatBritain": 10,
        "lithuania": 10,
        "latvia": 12,
        "estonia": 55,
        "ussr": -10,
        "norway": 20, 
        "germany": 25,
        "netherland": 3,
        "belgium": 2,
        "france": 7,
        "spain": 8,
        "portugal": 3,
        "italy": 5,
        "yugoslavia": 5,
        "albania": 1,
        "greece": 2,
        "turkey": 2,
        "bulgaria": 1,
        "romania": 1,
        "iceland": 5,
        "ireland" : 1,
        "czechoslovakia": 1,
        "hungary": 1,
        "austria" : 2,
        "switzerland" : 10,
        "sardynia" : 1,
        "sicily" : 2,
        "corsica" : 4,
        "eastPrussia" : 20,
        "algieria" : 1
    },
    denmark:{ 
        "poland": 0,
        "sweden": 20,
        "finland": 17,
        "greatBritain": 5,
        "lithuania": 4,
        "latvia": 0,
        "estonia": 15,
        "ussr": 0,
        "norway": 20,
        "germany": 15,
        "netherland": 0,
        "belgium": 0,
        "france": 0,
        "spain": 0,
        "portugal": 0,
        "italy": 0,
        "yugoslavia": 0,
        "albania": 0,
        "greece": 0,
        "turkey": 0,
        "bulgaria": 2,
        "romania": 5,
        "iceland": 15,
        "ireland" : 2,
        "czechoslovakia": 2,
        "hungary": 2,
        "austria" : 1,
        "switzerland" : 12,
        "sardynia" : 1,
        "sicily" : 2,
        "corsica" : 1,
        "eastPrussia" : 10,
        "algieria" : 1
    },
    greatBritain:{ 
        "poland": 32,
        "sweden": 12,
        "finland": 10,
        "denmark": 10,
        "lithuania": 15, 
        "latvia": 12,
        "estonia": 10,
        "ussr": -5,
        "norway": 14, 
        "germany": 0,
        "netherland": 22,
        "belgium": 22,
        "france": 55,
        "spain": 35,
        "portugal": 40,
        "italy": 3,
        "yugoslavia": 15,
        "albania": 5,
        "greece": 25,
        "turkey": 3,
        "bulgaria": 2,
        "romania": 10,
        "iceland": 10,
        "ireland" : 42,
        "czechoslovakia": 5,
        "hungary": 2,
        "austria" : 0,
        "switzerland" : 35,
        "sardynia" : 1,
        "sicily" : 1,
        "corsica" : 1,
        "eastPrussia" : 0,
        "algieria" : 1
    },
    lithuania:{ 
        "poland": -35,
        "sweden": 5,
        "finland": 5,
        "denmark": 5,
        "greatBritain": 25, 
        "latvia": 55, 
        "estonia": 52,
        "ussr": 0,
        "norway": 16, 
        "germany": 2,
        "netherland": 5,
        "belgium": 5,
        "france": 30,
        "spain": 7,
        "portugal": 5,
        "italy": 5,
        "yugoslavia": 3,
        "albania": 3,
        "greece": 7,
        "turkey": 2,
        "bulgaria": 2,
        "romania": 10,
        "iceland": 3,
        "ireland" : 5,
        "czechoslovakia": 5,
        "hungary": 2,
        "austria" : 1,
        "switzerland" : 5,
        "sardynia" : 1,
        "sicily" : 1,
        "corsica" : 1,
        "eastPrussia" : 0,
        "algieria" : 1
    },
    latvia:{ 
        "poland": 35,
        "sweden": 18,
        "finland": 15,
        "denmark": 17,
        "greatBritain": 25, 
        "lithuania": 43, 
        "estonia": 51,
        "ussr": -5,
        "norway": 5, 
        "germany": 5,
        "netherland": 5,
        "belgium": 5,
        "france": 25,
        "spain": 18,
        "portugal": 10,
        "italy": 5,
        "yugoslavia": 7,
        "albania": 6,
        "greece": 7,
        "turkey": 7,
        "bulgaria": 7,
        "romania": 7,
        "iceland": 3,
        "ireland" : 5,
        "czechoslovakia": 3,
        "hungary": 2,
        "austria" : 1,
        "switzerland" : 7,
        "sardynia" : 1,
        "sicily" : 1,
        "corsica" : 5,
        "eastPrussia" : -5,
        "algieria" : 1
    },
    estonia:{ 
        "poland": 35,
        "sweden": 41,
        "finland": 88,
        "denmark": 17,
        "greatBritain": 40, 
        "lithuania": 45, 
        "latvia": 53,
        "ussr": -10,
        "norway": 12, 
        "germany": 7,
        "netherland": 2,
        "belgium": 2,
        "france": 18,
        "spain": 8,
        "portugal": 3,
        "italy": 5,
        "yugoslavia": 5,
        "albania": 5,
        "greece": 5,
        "turkey": 5,
        "bulgaria": 1,
        "romania": 1,
        "iceland": 1,
        "ireland" : 2,
        "czechoslovakia": 3,
        "hungary": 2,
        "austria" : 1,
        "switzerland" : 1,
        "sardynia" : 1,
        "sicily" : 1,
        "corsica" : 8,
        "eastPrussia" : -5,
        "algieria" : 1
    },
    ussr:{ 
        "poland": -5,
        "sweden": 0,
        "finland": 0,
        "denmark": 0,
        "greatBritain": 0, 
        "lithuania": -5, 
        "latvia": -5,
        "estonia": -5,
        "norway": 0, 
        "germany": 15,
        "netherland": 1,
        "belgium": 1,
        "france": 0,
        "spain": 2,
        "portugal": 2,
        "italy": -5,
        "yugoslavia": 0,
        "albania": 0,
        "greece": 0,
        "turkey": 0,
        "bulgaria": 0,
        "romania": 0,
        "iceland": 0,
        "ireland" : 0,
        "czechoslovakia": 15,
        "hungary": 0,
        "austria" : 0,
        "switzerland" : 16,
        "sardynia" : 3,
        "sicily" : 3,
        "corsica" : 2,
        "eastPrussia" : 0,
        "algieria" : 1
    },
    norway:{ 
        "poland": 5,
        "sweden": 55,
        "denmark": 45,
        "greatBritain": 35,
        "lithuania": 5,
        "latvia": 7,
        "estonia": 12,
        "ussr": 0,
        "finland": 22,
        "germany": 0,
        "netherland": 5,
        "belgium": 5,
        "france": 15,
        "spain": 10,
        "portugal": 6,
        "italy": 5,
        "yugoslavia": 2,
        "albania": 2,
        "greece": 2,
        "turkey": 2,
        "bulgaria": 2,
        "romania": 2,
        "iceland": 2,
        "ireland" : 2,
        "czechoslovakia": 3,
        "hungary": 2,
        "austria" : 1,
        "switzerland" : 1,
        "sardynia" : 1,
        "sicily" : 1,
        "corsica" : 1,
        "eastPrussia" : 1,
        "algieria" : 1
    },
    germany:{ 
        "poland": 0,
        "sweden": 11,
        "finland": 20,
        "denmark": 0,
        "greatBritain": 0,
        "lithuania": 5,
        "latvia": 7,
        "estonia": 9,
        "ussr": 5,
        "norway": 5,
        "netherland": 15,
        "belgium": 5,
        "france": 0,
        "spain": 18,
        "portugal": 5,
        "italy": 65,
        "yugoslavia": 22,
        "albania": 0,
        "greece": 10,
        "turkey": 35,
        "bulgaria": 37,
        "romania": 25,
        "iceland": 5,
        "ireland" : 5,
        "czechoslovakia": 5,
        "hungary": 28,
        "austria" : 88,
        "switzerland" : 35,
        "sardynia" : 35,
        "sicily" : 30,
        "corsica" : 5,
        "eastPrussia" : 100,
        "algieria" : 1
    },
    netherland:{ 
        "poland": 5,
        "sweden": 5,
        "finland": 2,
        "denmark": 15,
        "greatBritain": 51,
        "lithuania": 5,
        "latvia": 5,
        "estonia": 2,
        "ussr": 5,
        "norway": 5,
        "germany": 15,
        "belgium": 35,
        "france": 35,
        "spain": 12,
        "portugal": 8,
        "italy": 15,
        "yugoslavia": 10,
        "albania": 4,
        "greece": 2,
        "turkey": 8,
        "bulgaria": 2,
        "romania": 2,
        "iceland": 2,
        "ireland" : 11,
        "czechoslovakia": 3,
        "hungary":2,
        "austria" : 1,
        "switzerland" : 16,
        "sardynia" : 2,
        "sicily" : 3,
        "corsica" : 8,
        "eastPrussia" : 12,
        "algieria" : 1
    },
    belgium:{ 
        "poland": 5,
        "sweden": 5,
        "finland": 5,
        "denmark": 5,
        "greatBritain": 47,
        "lithuania": 5,
        "latvia": 5,
        "estonia": 5,
        "ussr": 5,
        "norway": 12,
        "germany": 15,
        "netherland": 50,
        "france": 85,
        "spain": 14,
        "portugal": 19,
        "italy": 10,
        "yugoslavia": 12,
        "albania": 8,
        "greece": 1,
        "turkey": 7,
        "bulgaria": 0,
        "romania": 1,
        "iceland": 2,
        "ireland" : 1,
        "czechoslovakia": 5,
        "hungary": 1,
        "austria" : 1,
        "switzerland" : 1,
        "sardynia" : 1,
        "sicily" : 3,
        "corsica" : 1,
        "eastPrussia" : 1,
        "algieria" : 1
    },
    france:{ 
        "poland": 25,
        "sweden": 2,
        "finland": 2,
        "denmark": 5,
        "greatBritain": 65,
        "lithuania": 10,
        "latvia": 7,
        "estonia": 5,
        "ussr": 10,
        "norway": 5,
        "germany": -5,
        "netherland": 10,
        "belgium": 25,
        "spain": 25,
        "portugal": 15,
        "italy": 5,
        "yugoslavia": 10,
        "albania": 5,
        "greece": 5,
        "turkey": 10,
        "bulgaria": 5,
        "romania": 15,
        "iceland": 2,
        "ireland" : 15,
        "czechoslovakia": 35,
        "hungary": 5,
        "austria" : 1,
        "switzerland" : 35,
        "sardynia" : 3,
        "sicily" : 5,
        "corsica" : 100,
        "eastPrussia" :0,
        "algieria" : 35
    },
    spain:{ 
        "poland": 10,
        "sweden": 8,
        "finland": 8,
        "denmark": 8,
        "greatBritain": 25,
        "lithuania": 2,
        "latvia": 2,
        "estonia": 2,
        "ussr": 15,
        "norway": 5,
        "germany": 15,
        "netherland": 5,
        "belgium": 5,
        "france": 25,
        "portugal": 55,
        "italy": 15,
        "yugoslavia": 4,
        "albania": 3,
        "greece": 7,
        "turkey": 5,
        "bulgaria": 1,
        "romania": 4,
        "iceland": 2,
        "ireland" : 2,
        "czechoslovakia": 3,
        "hungary":2,
        "austria" : 1,
        "switzerland" : 1,
        "sardynia" : 5,
        "sicily" : 7,
        "corsica" : 5,
        "eastPrussia" : 7,
        "algieria" : 12
    },
    portugal:{ 
        "poland": 2,
        "sweden": 3,
        "finland": 4,
        "denmark": 3,
        "greatBritain": 75,
        "lithuania": 3,
        "latvia": 3,
        "estonia": 2,
        "ussr": 4,
        "norway": 2,
        "germany": 10,
        "netherland": 5,
        "belgium": 19,
        "france": 15,
        "spain": 55,
        "italy": 10,
        "yugoslavia": 6,
        "albania": 2,
        "greece": 2,
        "turkey": 8,
        "bulgaria": 2,
        "romania": 4,
        "iceland": 2,
        "ireland" : 1,
        "czechoslovakia": 3,
        "hungary":2,
        "austria" : 1,
        "switzerland" : 1,
        "sardynia" : 2,
        "sicily" : 3,
        "corsica" : 2,
        "eastPrussia" : 1,
        "algieria" : 18
    },
    italy:{ 
        "poland": 8,
        "sweden": 3,
        "finland": 2,
        "denmark": 1,
        "greatBritain": 5,
        "lithuania": 3,
        "latvia": 5,
        "estonia": 6,
        "ussr": -5,
        "norway": 5,
        "germany": 75,
        "netherland": 5,
        "belgium": 5,
        "france": 15,
        "spain": 25,
        "portugal": 15,
        "yugoslavia": 15,
        "albania": 25,
        "greece": 15,
        "turkey": 12,
        "bulgaria": 15,
        "romania": 17,
        "iceland": 2,
        "ireland" : 2,
        "czechoslovakia": 2,
        "hungary": 8,
        "austria" : 25,
        "switzerland" : 23,
        "sardynia" : 55,
        "sicily" : 88,
        "corsica" : 30,
        "eastPrussia" : 32,
        "algieria" : 22
    },
    yugoslavia:{
        "poland": 15,
        "sweden": 5,
        "finland": 1,
        "denmark": 3,
        "greatBritain": 33,
        "lithuania": 2,
        "latvia": 3,
        "estonia": 2,
        "ussr": 15,
        "norway": 11,
        "germany": 15,
        "netherland": 15,
        "belgium": 14,
        "france": 28,
        "spain": 15,
        "portugal": 18,
        "italy": 45,
        "albania": 22,
        "greece": 25,
        "turkey": 26,
        "bulgaria": 28,
        "romania": 35,
        "iceland": 1,
        "ireland" : 2,
        "czechoslovakia": 31,
        "hungary": 30,
        "austria" : 28,
        "switzerland" : 23,
        "sardynia" : 22,
        "sicily" : 3,
        "corsica" : 8,
        "eastPrussia" : 3,
        "algieria" : 1
    },
    albania:{ 
        "poland": 1,
        "sweden": 3,
        "finland": 1,
        "denmark": 1,
        "greatBritain": 7,
        "lithuania": 1,
        "latvia": 1,
        "estonia": 1,
        "ussr": 4,
        "norway": 1,
        "germany": 11,
        "netherland": 1,
        "belgium": 1,
        "france": 3,
        "spain": 2,
        "portugal": 1,
        "italy": 22,
        "yugoslavia": 15,
        "greece": 18,
        "turkey": 12,
        "bulgaria": 11,
        "romania": 8,
        "iceland": 1,
        "ireland" : 1,
        "czechoslovakia": 2,
        "hungary": 3,
        "austria" : 2,
        "switzerland" : 1,
        "sardynia" : 12,
        "sicily" : 12,
        "corsica" : 1,
        "eastPrussia" : 1,
        "algieria" : 1
    },
    greece:{ 
        "poland": 5,
        "sweden": 5,
        "finland": 3,
        "denmark": 5,
        "greatBritain": 52,
        "lithuania": 2,
        "latvia": 3,
        "estonia": 2,
        "ussr": 15,
        "norway": 3,
        "germany": 25,
        "netherland": 10,
        "belgium": 8,
        "france": 40,
        "spain": 42,
        "portugal": 12,
        "italy": 35,
        "yugoslavia": 40,
        "albania": 35,
        "turkey": 35,
        "bulgaria": 30,
        "romania": 28,
        "iceland": 1,
        "ireland" : 1,
        "czechoslovakia": 3,
        "hungary": 3,
        "austria" : 3,
        "switzerland" : 5,
        "sardynia" : 13,
        "sicily" : 7,
        "corsica" : 5,
        "eastPrussia" : 1,
        "algieria" : 3
    },
    turkey:{ 
        "poland": 7,
        "sweden": 5,
        "finland": 3,
        "denmark": 4,
        "greatBritain": 31,
        "lithuania": 2,
        "latvia": 2,
        "estonia": 1,
        "ussr": 25,
        "norway": 1,
        "germany": 51,
        "netherland": 2,
        "belgium": 3,
        "france": 32,
        "spain": 23,
        "portugal": 22,
        "italy": 25,
        "yugoslavia": 22,
        "albania": 23,
        "greece": 31,
        "bulgaria": 34,
        "romania": 30,
        "iceland": 2,
        "ireland" : 2,
        "czechoslovakia": 5,
        "hungary": 7,
        "austria" : 5,
        "switzerland" : 3,
        "sardynia" : 12,
        "sicily" : 7,
        "corsica" : 5,
        "eastPrussia" : 31,
        "algieria" : 30
    },
    bulgaria:{ 
        "poland": 5,
        "sweden": 1,
        "finland": 1,
        "denmark": 1,
        "greatBritain": 12,
        "lithuania": 1,
        "latvia": 1,
        "estonia": 1,
        "ussr": 22,
        "norway": 1,
        "germany": 18,
        "netherland": 3,
        "belgium": 2,
        "france": 13,
        "spain": 8,
        "portugal": 5,
        "italy": 17,
        "yugoslavia": 43,
        "albania": 22,
        "greece": 45,
        "turkey": 71,
        "romania": 80,
        "iceland": 1,
        "ireland" : 1,
        "czechoslovakia": 18,
        "hungary": 28,
        "austria" : 21,
        "switzerland" : 16,
        "sardynia" : 5,
        "sicily" : 8,
        "corsica" : 7,
        "eastPrussia" : 2,
        "algieria" : 18
    },
    romania:{ 
        "poland": 41,
        "sweden": 5,
        "finland": 3,
        "denmark": 4,
        "greatBritain": 22,
        "lithuania": 1,
        "latvia": 1,
        "estonia": 1,
        "ussr": 38,
        "norway": 1,
        "germany": 22,
        "netherland": 11,
        "belgium": 9,
        "france": 21,
        "spain": 13,
        "portugal": 8,
        "italy": 18,
        "yugoslavia": 38,
        "albania": 35,
        "greece": 22,
        "turkey": 22,
        "bulgaria": 71,
        "iceland": 1,
        "ireland" : 1,
        "czechoslovakia": 35,
        "hungary": 71,
        "austria" : 55,
        "switzerland" : 15,
        "sardynia" : 3,
        "sicily" : 3,
        "corsica" : 8,
        "eastPrussia" : 12,
        "algieria" : 3
    },
    iceland:{ 
        "poland": 3,
        "sweden": 3,
        "finland": 3,
        "denmark": 2,
        "greatBritain": 23,
        "lithuania": 1,
        "latvia": 1,
        "estonia": 1,
        "ussr": 15,
        "norway": 1,
        "germany": 20,
        "netherland": 5,
        "belgium": 3,
        "france": 12,
        "spain": 13,
        "portugal": 5,
        "italy": 5,
        "yugoslavia": 1,
        "albania": 1,
        "greece": 2,
        "turkey": 1,
        "bulgaria": 1,
        "romania": 1,
        "ireland" : 1,
        "czechoslovakia": 2,
        "hungary": 2,
        "austria" : 1,
        "switzerland" : 5,
        "sardynia" : 1,
        "sicily" : 1,
        "corsica" : 1,
        "eastPrussia" : 3,
        "algieria" : 1
    },
    ireland:{ 
        "poland": 0,
        "sweden": 8,
        "finland": 5,
        "denmark": 7,
        "greatBritain": 88,
        "lithuania": 2, 
        "latvia": 1,
        "estonia": 1,
        "ussr": 13,
        "norway": 22, 
        "germany": 31,
        "netherland": 18,
        "belgium": 5,
        "france": 31,
        "spain": 11,
        "portugal": 5,
        "italy": 12,
        "yugoslavia": 4,
        "albania": 1,
        "greece": 3,
        "turkey": 5,
        "bulgaria": 2,
        "romania": 5,
        "iceland": 5 ,
        "czechoslovakia": 3,
        "hungary":2,
        "austria" : 1,
        "switzerland" : 13,
        "sardynia" : 1,
        "sicily" : 10,
        "corsica" : 20,
        "eastPrussia" : 12,
        "algieria" : 1
    },
    czechoslovakia:{ 
        "poland": -5,
        "sweden": 11,
        "finland": 8,
        "denmark": 8,
        "greatBritain": 28,
        "lithuania": 8, 
        "latvia": 7,
        "estonia": 5,
        "ussr": 18,
        "norway": 5, 
        "germany": 82,
        "netherland": 7,
        "belgium": 6,
        "france": 31,
        "spain": 18,
        "portugal": 12,
        "italy": 31,
        "yugoslavia": 35,
        "albania": 5,
        "greece": 5,
        "turkey": 5,
        "bulgaria": 5,
        "romania": 30,
        "iceland": 1,
        "hungary": 45,
        "austria": 42,
        "switzerland" : 22,
        "ireland" : 2,
        "sardynia" : 1,
        "sicily" : 2,
        "corsica" : 2,
        "eastPrussia" : 31,
        "algieria" : 1
    },
    hungary:{ 
        "poland": 40,
        "sweden": 12,
        "finland": 5,
        "denmark": 7,
        "greatBritain": 22,
        "lithuania": 3, 
        "latvia": 3,
        "estonia": 2,
        "ussr": 25,
        "norway": 2, 
        "germany": 25,
        "netherland": 3,
        "belgium": 2,
        "france": 23,
        "spain": 17,
        "portugal": 6,
        "italy": 21,
        "yugoslavia": 63,
        "albania": 12,
        "greece": 15,
        "turkey": 15,
        "bulgaria": 22,
        "romania": 55,
        "iceland": 1 ,
        "czechoslovakia": 52,
        "austria": 72,
        "switzerland" : 18,
        "ireland" : 1,
        "sardynia" : 2,
        "sicily" : 1,
        "corsica" : 1,
        "eastPrussia" : 12,
        "algieria" : 1
    },
    austria:{ 
        "poland": 5,
        "sweden": 4,
        "finland": 3,
        "denmark": 4,
        "greatBritain": 7,
        "lithuania": 7, 
        "latvia": 6,
        "estonia": 5,
        "ussr": 2,
        "norway": 2, 
        "germany": 90,
        "netherland": 3,
        "belgium": 2,
        "france": 12,
        "spain": 7,
        "portugal": 3,
        "italy": 71,
        "yugoslavia": 45,
        "albania": 2,
        "greece": 2,
        "turkey": 2,
        "bulgaria": 2,
        "romania": 3,
        "iceland": 1 ,
        "czechoslovakia": 0,
        "hungary": 0,
        "switzerland" : 45,
        "ireland" : 1,
        "sardynia" : 1,
        "sicily" : 1,
        "corsica" : 1,
        "eastPrussia" : 12,
        "algieria" : 1
    },
    switzerland:{ 
        "poland": 12,
        "sweden": 7,
        "finland": 3,
        "denmark": 3,
        "greatBritain": 48,
        "lithuania": 1, 
        "latvia": 1,
        "estonia": 1,
        "ussr": 45,
        "norway": 1, 
        "germany": 83,
        "netherland": 21,
        "belgium": 18,
        "france": 82,
        "spain": 5,
        "portugal": 3,
        "italy": 80,
        "yugoslavia": 31,
        "albania": 2,
        "greece": 31,
        "turkey": 28,
        "bulgaria": 2,
        "romania": 3,
        "iceland": 3 ,
        "czechoslovakia": 12,
        "hungary": 3,
        "austria" : 22,
        "ireland" : 1,
        "sardynia" : 5,
        "sicily" : 10,
        "corsica" : 1,
        "eastPrussia" : 5,
        "algieria" : 1
    },
    eastPrussia:{ 
        "poland": -30,
        "sweden": 31,
        "finland": 22,
        "denmark": 23,
        "greatBritain": 15,
        "lithuania": 55, 
        "latvia": 5,
        "estonia": 7,
        "ussr": 12,
        "norway": 13, 
        "germany": 100,
        "netherland": 21,
        "belgium": 3,
        "france": 5,
        "spain": 17,
        "portugal": 2,
        "italy": 23,
        "yugoslavia": 2,
        "albania": 1,
        "greece": 2,
        "turkey": 12,
        "bulgaria": 2,
        "romania": 2,
        "iceland": 1 ,
        "czechoslovakia": 3,
        "hungary":3,
        "austria" : 15,
        "ireland" : 1,
        "sardynia" : 2,
        "sicily" : 1,
        "corsica" : 1,
        "algieria" : 1,
        "switzerland" : 15
    },
    corsica:{ 
        "poland": 2,
        "sweden": 2,
        "finland": 2,
        "denmark": 1,
        "greatBritain": 5,
        "lithuania": 3, 
        "latvia": 2,
        "estonia": 2,
        "ussr": 7,
        "norway": 2, 
        "germany": 6,
        "netherland": 2,
        "belgium": 2,
        "france": 22,
        "spain": 8,
        "portugal": 3,
        "italy": 12,
        "yugoslavia": 3,
        "albania": 1,
        "greece": 3,
        "turkey": 3,
        "bulgaria": 2,
        "romania": 2,
        "iceland": 1 ,
        "czechoslovakia": 1,
        "hungary":1,
        "austria" : 1,
        "ireland" : 1,
        "sardynia" : 2,
        "sicily" : 2,
        "eastPrussia" : 1,
        "algieria" : 1,
        "switzerland" : 5
    },
    algieria:{ 
        "poland": 2,
        "sweden": 1,
        "finland": 1,
        "denmark": 1,
        "greatBritain": 5,
        "lithuania": 1, 
        "latvia": 1,
        "estonia": 1,
        "ussr": 3,
        "norway": 1, 
        "germany": 3,
        "netherland": 1,
        "belgium": 1,
        "france": 21,
        "spain": 12,
        "portugal": 7,
        "italy": 5,
        "yugoslavia": 3,
        "albania": 3,
        "greece": 3,
        "turkey": 3,
        "bulgaria": 2,
        "romania": 2,
        "iceland": 1 ,
        "czechoslovakia": 1,
        "hungary": 1,
        "austria" : 1,
        "ireland" : 1,
        "sardynia" : 3,
        "sicily" : 2,
        "corsica" : 1,
        "eastPrussia" : 1,
        "switzerland" : 2
    },
    sicily:{ 
        "poland": 2,
        "sweden": 2,
        "finland": 2,
        "denmark": 2,
        "greatBritain": 5,
        "lithuania": 1, 
        "latvia": 1,
        "estonia": 1,
        "ussr": 3,
        "norway": 1, 
        "germany": 12,
        "netherland": 3,
        "belgium": 3,
        "france": 5,
        "spain": 7,
        "portugal": 3,
        "italy": 88,
        "yugoslavia": 3,
        "albania": 12,
        "greece": 7,
        "turkey": 7,
        "bulgaria": 8,
        "romania": 3,
        "iceland": 1 ,
        "czechoslovakia": 2,
        "hungary": 1,
        "austria" : 1,
        "switzerland" : 10,
        "ireland" : 10,
        "sardynia" : 22,
        "corsica" : 2,
        "eastPrussia" : 1,
        "algieria" : 2
    },
    sardynia:{ 
        "poland": 1,
        "sweden": 1,
        "finland": 1,
        "denmark": 1,
        "greatBritain": 5,
        "lithuania": 1, 
        "latvia": 1,
        "estonia": 1,
        "ussr": 3,
        "norway": 1, 
        "germany": 8,
        "netherland": 2,
        "belgium": 1,
        "france": 3,
        "spain": 5,
        "portugal": 2,
        "italy": 37,
        "yugoslavia": 22,
        "albania": 12,
        "greece": 13,
        "turkey": 12,
        "bulgaria": 5,
        "romania": 3,
        "iceland": 1 ,
        "czechoslovakia": 1,
        "hungary":2,
        "austria" : 1,
        "switzerland" : 5,
        "ireland" : 1,
        "sicily" : 22,
        "corsica" : 2,
        "eastPrussia" : 2,
        "algieria" : 3
    }
}

export function increaseRelations(){

}


//TODO should go equalize each day
export function equalizeRelations(){
    
}